export const PRODUCT_INFO = 'PRODUCT_INFO';
export const SET_BUYITEMS_INFO = 'SET_BUYITEMS_INFO';
export const ADD_BUYITEMS_INFO = 'ADD_BUYITEMS_INFO';
export const SET_MODAL_STATUS = 'SET_MODAL_STATUS';
export const SET_STRIPE_CLIENT_SECRET = 'SET_STRIPE_CLIENT_SECRET';